import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HMButton from "../component/Button/Button";
import Layout from "../component/Layout/Layout";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <header>
        <div className={styles.headerLogo}>
          <Image
            src="/images/logo.jpeg" // Route of the image file
            height={44} // Desired size with correct aspect ratio
            width={68} // Desired size with correct aspect ratio
            alt="Logo"
          />
        </div>
      </header>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <h1 className={styles.header}>OUR GIFT CARDS</h1>
            <div className={styles.landingLogo}>
              <Image
                src="/images/landingPage.jpeg" // Route of the image file
                height={271} // Desired size with correct aspect ratio
                width={1400} // Desired size with correct aspect ratio
                alt="Card"
              />
            </div>
            <div className={styles.optionButtonGroup}>
              <HMButton
                className={styles.buttonContainer}
                text="E-Gift Card"
                onClick={() => {
                  router.push(`/gift-card/e-gift-card`);
                }}
              ></HMButton>
              <HMButton
                className={styles.buttonContainer}
                text="Corporate/Bulk Card"
                onClick={() => {
                  router.push(`/corporate-card/corporate-card`);
                }}
              ></HMButton>
              <HMButton
                className={styles.buttonContainer}
                text="Physical Gift Card"
                // onClick={() => handleCategory("All")}
              ></HMButton>
            </div>
            <div>
              <p>
                Are you looking for the perfect gift idea? With an H&M Gift
                Card, your special someone can choose the perfect gift at any
                H&M store in India and on hm.com.
              </p>
            </div>

            <div>
              All you have to do is select your favorite design - is Christmas
              time approaching? Choose a Gift Card with a Christmas design. Is
              it someone's birthday? You can choose from tons of birthday
              greeting cards. Then, choose the amount you want to upload, add a
              personal message and that's it!
            </div>
            <div>
              <p>
                When it comes to making a romantic gesture or giving something
                fun for Christmas or a special occasion, a Gift Card is always
                the right choice. In addition, digital gift cards can be the
                perfect solution for a last minute gift.
              </p>
            </div>
            <div className={styles.InfoDescription}>
              <h1>All you need to know about purchasing digital gift cards</h1>
            </div>
            <div>
              <ul>
                <li>
                  Where can it be used? Your Gift Card can be used in the
                  country where it was purchased, both online and in-store.
                </li>
                <li>
                  You can use your H&M Gift Card to make full or partial
                  payments.{" "}
                </li>
                <li>
                  The desired amount will be deducted from your Gift Card and
                  any remaining balance will be shown on the receipt.
                </li>
                <li>To top up your physical Gift Card, visit an H&M store.</li>
              </ul>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
